# Generated by Django 6.0.3 on 2026-04-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.CharField(),
        ),
    ]
