# Generated by Django 6.0.3 on 2026-04-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='feedback',
            field=models.TextField(default=None),
        ),
    ]
