c = eval(input("enter a data: "))
print(c)
d = eval(input("Enter append num: "))
c.append(d)
print(c)
e = eval(input("Enter insert num: "))
c.insert(1,e)
print(c)
c.pop()
print(c)
f = eval(input("Enter the index: "))
c.pop(f)
print(c)