# Generated by Django 6.0.3 on 2026-04-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
